In [ ]:
import numpy as np

a = np.array([0, 1, 2])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# Create a rank 2 array:
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [3]:
# Create a 3x3 array of all zeros:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# Create a 2x2 array of all ones:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [6]:
# Create a 3x3 constant array:
c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [7]:
# Create a 3x3 array filled with random values:
d = np.random.random((3,3))
print (d)

[[0.61225694 0.94478852 0.96622815]
 [0.75007073 0.81072235 0.01795579]
 [0.60916901 0.83108975 0.08935802]]


In [8]:
# Create a 3x3 identity matrix:
e = np.eye(3)
print (e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print (h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [12]:
j = np.linspace(2., 4., 7)
print (j)

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.        ]


In [14]:
# linspace() will create arrays with a specified number of items which are spaced equally between the specified beginning and end values:
k = np.indices((3,2))
print (k)

[[[0 0]
  [1 1]
  [2 2]]

 [[0 1]
  [0 1]
  [0 1]]]


In [15]:
# indices() will create a set of arrays stacked as a one-higher dimensioned array, one per dimension with each representing variation in that dimension.
k = np.indices((2,2))
print (k)

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]


In [17]:
# basic slicing
x = np.array([5, 6, 7, 8, 9])
print(x[1:7:2])

[6 8]


In [20]:
y = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print ("Shape of y: ", y.shape, "\n", y[1:3])

Shape of y:  (2, 3, 1) 
 [[[4]
  [5]
  [6]]]


In [21]:
a = np.array([[5,6,7,8], [1,2,3,4], [9,10,11,12]])
b = a[:2, 1:3]
print ("Array b:", b)

Array b: [[6 7]
 [2 3]]


In [25]:
# boolean
a=np.array([[1,2], [3, 4], [5, 6]])
print (a > 2)
print (a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [27]:
# array math
x=np.array([[1,2],[3,4],[5,6]])
y=np.array([[7,8],[9,10],[11,12]])
print(x+y)
print(np.add(x, y))
print(x-y)
print(np.subtract(x, y))

[[ 8 10]
 [12 14]
 [16 18]]
[[ 8 10]
 [12 14]
 [16 18]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]
[[-6 -6]
 [-6 -6]
 [-6 -6]]


In [28]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
a=np.array([9,10])
b=np.array([11, 12])
print(a.dot(b))
print(np.dot(a, b))

219
219
